/**
 * Canonical live API route reference for React repositories.
 * Repositories must consume these constants instead of hardcoding endpoint paths.
 */

export const resolvePath = (path: string, params: Record<string, string>) =>
  Object.entries(params).reduce(
    (resolvedPath, [key, value]) => resolvedPath.replace(`:${key}`, value),
    path,
  );

export const MasterApiReference = {
  Auth: {
    SendOtp: '/auth/send-otp',
    VerifyOtp: '/auth/verify-otp',
    VerifyPin: '/auth/verify-pin',
    RefreshToken: '/auth/refresh-token',
    Me: '/auth/me',
    RevokeToken: '/auth/revoke-token',
  },
  Admin: {
    Dashboard: '/admin/dashboard',
    Families: '/admin/families',
    Plans: '/admin/plans',
    RewardCatalog: '/admin/rewards/catalog',
    RewardCatalogItem: '/admin/rewards/catalog/:rewardId',
    TaskTemplates: '/admin/task-templates',
    FeatureFlags: '/admin/feature-flags',
    FeatureFlag: '/admin/feature-flags/:flagId',
    NotificationCampaign: '/admin/notifications/campaign',
  },
  Families: {
    Root: '/families',
    Members: '/families/:familyId/members',
    JoinCode: '/families/:familyId/join-code',
    RegenerateJoinCode: '/families/:familyId/join-code/regenerate',
    ChildrenByJoinCode: '/families/children',
    Dashboard: '/families/:familyId/dashboard',
    Goals: '/families/:familyId/goals',
    Goal: '/families/:familyId/goals/:goalId',
    Child: '/families/:familyId/children/:childId',
  },
  Attendance: {
    ListSessions: '/families/:familyId/attendance/sessions',
    SessionRecords: '/families/:familyId/attendance/sessions/:sessionId/records',
    SubmitSession: '/families/:familyId/attendance/sessions/:sessionId/submit',
    CommentTemplates: '/families/:familyId/comment-templates',
    CreateSession: '/families/:familyId/attendance/sessions',
  },
  Tasks: {
    FamilyTasks: '/families/:familyId/tasks',
    FamilyTask: '/families/:familyId/tasks/:taskId',
    FamilyTaskCompletions: '/families/:familyId/tasks/completions',
    VerificationQueue: '/families/:familyId/tasks/verification-queue',
    ApproveAllVerificationQueue: '/families/:familyId/tasks/verification-queue/approve-all',
    UploadUrl: '/families/:familyId/tasks/completions/upload-url',
    TaskCompletions: '/families/:familyId/tasks/:taskId/completions',
    TaskCompletionReview: '/families/:familyId/tasks/completions/:completionId/review',
    ExamMode: '/families/:familyId/tasks/exam-mode',
  },
  Feedback: {
    FamilyFeedback: '/families/:familyId/feedback',
    FamilyFeedbackItem: '/families/:familyId/feedback/:feedbackId',
    Acknowledge: '/feedback/:feedbackId/acknowledge',
  },
  Rewards: {
    FamilyRewards: '/families/:familyId/rewards',
    FamilyReward: '/families/:familyId/rewards/:rewardId',
    CoinHistory: '/children/:childId/coin-history',
    Redeem: '/families/:familyId/rewards/:rewardId/redeem',
    Redemptions: '/families/:familyId/rewards/redemptions',
    Redemption: '/families/:familyId/rewards/redemptions/:redemptionId',
  },
  Children: {
    Detail: '/families/:familyId/children/:childId',
    ScoreHistory: '/children/:childId/score-history',
    Update: '/children/:childId',
    CoinDeduction: '/children/:childId/coin-deduction',
  },
  Elder: {
    Grandchildren: '/families/:familyId/members/grandchildren',
  },
  Calendar: {
    Events: '/families/:familyId/calendar/events',
    Event: '/families/:familyId/calendar/events/:eventId',
    Upcoming: '/families/:familyId/calendar/upcoming',
  },
  Notifications: {
    UserNotifications: '/users/:userId/notifications',
    UserNotificationRead: '/users/:userId/notifications/:notificationId/read',
    UserNotificationsReadAll: '/users/:userId/notifications/read-all',
    Preferences: '/users/:userId/notification-preferences',
  },
  FamilyAdmin: {
    Storage: '/families/:familyId/admin/storage',
    AlertThresholds: '/families/:familyId/admin/alert-thresholds',
    EmergencyConfig: '/families/:familyId/admin/emergency-config',
    FinanceConfig: '/families/:familyId/admin/finance-config',
    ModuleVisibility: '/families/:familyId/admin/module-visibility',
    NotificationRules: '/families/:familyId/admin/notification-rules',
    NotificationRule: '/families/:familyId/admin/notification-rules/:ruleId',
  },
  Finance: {
    Dashboard: '/families/:familyId/finance/dashboard',
    Transactions: '/families/:familyId/finance/transactions',
    TransactionQuestion: '/families/:familyId/finance/transactions/:transactionId/question',
    Budget: '/families/:familyId/finance/budget',
    Categories: '/families/:familyId/finance/categories',
    Commitments: '/families/:familyId/finance/commitments',
    ConsentInvite: '/families/:familyId/finance/consent/invite',
    ConsentMember: '/families/:familyId/finance/consent/:memberId',
    Settings: '/families/:familyId/finance/settings',
  },
  Safety: {
    Map: '/families/:familyId/safety/map',
    Location: '/families/:familyId/safety/location',
    Zones: '/families/:familyId/safety/zones',
    Zone: '/families/:familyId/safety/zones/:zoneId',
    Alerts: '/families/:familyId/safety/alerts',
    ResolveAlert: '/families/:familyId/safety/alerts/:alertId/resolve',
    Sos: '/families/:familyId/safety/sos',
    Settings: '/families/:familyId/safety/settings',
  },
  Medical: {
    HealthProfiles: '/families/:familyId/health-profiles',
    HealthProfile: '/families/:familyId/health-profiles/:memberId',
    Prescriptions: '/families/:familyId/health-profiles/:memberId/prescriptions',
    Prescription: '/families/:familyId/health-profiles/:memberId/prescriptions/:prescriptionId',
    Vaccinations: '/families/:familyId/health-profiles/:memberId/vaccinations',
    VaccinationStatus: '/families/:familyId/health-profiles/:memberId/vaccinations/:vaccinationId/status',
    Timeline: '/families/:familyId/health-profiles/:memberId/timeline',
    EmergencyCard: '/families/:familyId/health-profiles/:memberId/emergency-card',
    ShareEmergencyCard: '/families/:familyId/health-profiles/:memberId/emergency-card/share',
    EmergencyCardByToken: '/medical/emergency-card/:token',
    HeightWeight: '/families/:familyId/health-profiles/:memberId/height-weight',
  },
  Reports: {
    WeeklyDigest: '/families/:familyId/reports/weekly-digest',
    AttendanceSummary: '/children/:childId/reports/attendance-summary',
    MonthlyFamily: '/families/:familyId/reports/monthly',
    ChildMonthly: '/families/:familyId/children/:childId/reports/monthly',
    DocumentExpiry: '/families/:familyId/reports/documents/expiry',
    HealthReminders: '/families/:familyId/reports/health/reminders',
  },
  Vault: {
    UploadUrl: '/families/:familyId/vault/documents/upload-url',
    Documents: '/families/:familyId/vault/documents',
    Document: '/families/:familyId/vault/documents/:documentId',
    Expiry: '/families/:familyId/vault/expiry',
    Emergency: '/families/:familyId/vault/emergency',
    Share: '/families/:familyId/vault/documents/:documentId/share',
    ShareLink: '/families/:familyId/vault/documents/:documentId/share/:shareLinkId',
    ShareToken: '/vault/share/:token',
  },
  GetMasters: '/GetMasters',
} as const;
